#index:
#    path: /
#    controller: App\Controller\DefaultController::index



app_utlisateur:
    path: /
    controller: App\Controller\UtlisateurController::index



app_personne:
    path: /personne
    controller: App\Controller\UtlisateurController::personne


app_details:
    path: /details/{nom}
    controller: App\Controller\UtlisateurController::details

